# Generated by Django 3.0 on 2022-11-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='classe')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25, unique=True)),
                ('capacity', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('set', models.CharField(blank=True, max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='configuration.Classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='configuration.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='classe_subjects', through='configuration.SubjectsSet', to='configuration.Subjects'),
        ),
    ]
